services:
  - type: web
    name: shoestore-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    branch: main
    healthCheckPath: /
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JAVA_OPTS
        value: "-Xms256m -Xmx512m"
      - key: DATABASE_URL
        fromDatabase:
          name: shoestore-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: shoestore-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: shoestore-db
          property: password
      - key: SPRING_MAIL_USERNAME
        value: webshoestore17@gmail.com
      - key: SPRING_MAIL_PASSWORD
        value: quziuvvngrwrjzkp
      - key: CLOUDINARY_CLOUD_NAME
        value: dd4v8svrk
      - key: CLOUDINARY_API_KEY
        value: 533865834927859
      - key: CLOUDINARY_API_SECRET
        value: YPvKEOV7wpZ9sD3vVFcw08yS-7w

databases:
  - name: shoestore-db
    databaseName: postgres
    user: postgres
    plan: free
    region: singapore